// Code generated by Slice Machine. DO NOT EDIT.

import Footer from "./Footer/index.svelte";
import PageTitle from "./PageTitle/index.svelte";
import Project from "./Project/index.svelte";
import WelcomeText from "./WelcomeText/index.svelte";

export const components = {
	footer: Footer,
	page_title: PageTitle,
	project: Project,
	welcome_text: WelcomeText,
};
