// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type IndexDocumentDataSlicesSlice = PageTitleSlice | WelcomeTextSlice | FooterSlice;

/**
 * Content for Index documents
 */
interface IndexDocumentData {
	/**
	 * Slice Zone field in *Index*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<IndexDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *Index*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: index.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Index*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: index.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Index*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: index.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<IndexDocumentData>,
	"index",
	Lang
>;

type ProjectDocumentDataSlicesSlice = never;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * Slice Zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: project.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: project.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProjectDocumentData>,
	"project",
	Lang
>;

export type AllDocumentTypes = IndexDocument | ProjectDocument;

/**
 * Primary content in *Footer → Items*
 */
export interface FooterSliceDefaultItem {
	/**
	 * link field in *Footer → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
	"default",
	Record<string, never>,
	Simplify<FooterSliceDefaultItem>
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *PageTitle → Primary*
 */
export interface PageTitleSliceDefaultPrimary {
	/**
	 * title field in *PageTitle → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Default variation for PageTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageTitleSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<PageTitleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *PageTitle*
 */
type PageTitleSliceVariation = PageTitleSliceDefault;

/**
 * PageTitle Shared Slice
 *
 * - **API ID**: `page_title`
 * - **Description**: PageTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageTitleSlice = prismic.SharedSlice<"page_title", PageTitleSliceVariation>;

/**
 * Primary content in *Project → Primary*
 */
export interface ProjectSliceDefaultPrimary {
	/**
	 * title field in *Project → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * screenshot field in *Project → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.primary.screenshot
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	screenshot: prismic.ImageField<never>;

	/**
	 * description field in *Project → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *Project → Items*
 */
export interface ProjectSliceDefaultItem {
	/**
	 * more_info field in *Project → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.items[].more_info
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	more_info: prismic.RichTextField;
}

/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<ProjectSliceDefaultPrimary>,
	Simplify<ProjectSliceDefaultItem>
>;

/**
 * Slice variation for *Project*
 */
type ProjectSliceVariation = ProjectSliceDefault;

/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: Project
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSlice = prismic.SharedSlice<"project", ProjectSliceVariation>;

/**
 * Primary content in *WelcomeText → Primary*
 */
export interface WelcomeTextSliceDefaultPrimary {
	/**
	 * welcometext field in *WelcomeText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: welcome_text.primary.welcometext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	welcometext: prismic.RichTextField;
}

/**
 * Default variation for WelcomeText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeTextSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<WelcomeTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *WelcomeText*
 */
type WelcomeTextSliceVariation = WelcomeTextSliceDefault;

/**
 * WelcomeText Shared Slice
 *
 * - **API ID**: `welcome_text`
 * - **Description**: WelcomeText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeTextSlice = prismic.SharedSlice<"welcome_text", WelcomeTextSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			IndexDocument,
			IndexDocumentData,
			IndexDocumentDataSlicesSlice,
			ProjectDocument,
			ProjectDocumentData,
			ProjectDocumentDataSlicesSlice,
			AllDocumentTypes,
			FooterSlice,
			FooterSliceDefaultItem,
			FooterSliceVariation,
			FooterSliceDefault,
			PageTitleSlice,
			PageTitleSliceDefaultPrimary,
			PageTitleSliceVariation,
			PageTitleSliceDefault,
			ProjectSlice,
			ProjectSliceDefaultPrimary,
			ProjectSliceDefaultItem,
			ProjectSliceVariation,
			ProjectSliceDefault,
			WelcomeTextSlice,
			WelcomeTextSliceDefaultPrimary,
			WelcomeTextSliceVariation,
			WelcomeTextSliceDefault,
		};
	}
}
